version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: docker_files/backend/Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./backend:/rails6-chat-be
      - gem_data:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
    tty: true
    stdin_open: true

  db:
    image: mysql:8.0.28
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    tty: true
    stdin_open: true

  frontend:
    build:
      context: .
      dockerfile: docker_files/frontend/Dockerfile
    volumes:
      - ./frontend:/rails6-chat-fe
    ports:
      - '8080:8080'
    depends_on:
      - backend
    tty: true
    stdin_open: true
    command: npm run serve

volumes:
  gem_data:
  mysql-data: