source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.1.2'

gem 'rails', '~> 6.0.5', '>= 6.0.5.1'
gem 'mysql2', '~> 0.5.4'
gem 'puma', '~> 5.6', '>= 5.6.4'
gem 'jbuilder', '~> 2.11', '>= 2.11.5'
gem 'bcrypt', '~> 3.1', '>= 3.1.18'
gem "tzinfo-data", platforms: %i[ mingw mswin x64_mingw jruby ]
gem 'bootsnap', require: false
gem 'rack-cors'

gem 'net-smtp'
gem 'psych', '~> 3.1'

gem 'devise'
gem 'devise_token_auth'

group :development, :test do
  gem "debug", platforms: %i[ mri mingw x64_mingw ]
  gem "rspec-rails"
  gem "factory_bot_rails"
end

group :development do
  gem 'listen', '~> 3.2'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem "web-console"
end
