source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.1.2'

gem 'rails', '~> 6.0.5', '>= 6.0.5.1'
gem 'mysql2', '>= 0.4.4'
gem 'puma', '~> 4.1'
gem 'jbuilder', '~> 2.7'
gem "bcrypt", "~> 3.1.7"
gem "tzinfo-data", platforms: %i[ mingw mswin x64_mingw jruby ]
gem 'bootsnap', '>= 1.4.2', require: false
gem 'rack-cors'

gem 'net-smtp'
gem 'psych', '~> 3.1'


group :development, :test do
  gem "debug", platforms: %i[ mri mingw x64_mingw ]
  gem "web-console"
  gem "rspec-rails"
  gem "factory_bot_rails"
end

group :development do
  gem 'listen', '~> 3.2'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end
